// sprites.js — Kenney CC0 spritesheet loader and tile/region extraction
//
// As of v0.4.3-dev, Violencetown uses Kenney's Roguelike packs as its sole
// sprite source (CC0 1.0, committed under game/assets-placeholder/kenney/).
// An earlier dual-source setup (a separate primary art set with Kenney as
// fallback) was retired to remove dual-system overhead during early development.
//
// All sheets are 16×16 native; the renderer draws at TILE_PX=32 via destW/
// destH upscale params, so the 2× nearest-neighbor scale happens at draw
// time without pre-processing.

export class SpriteSheet {
    // `padding` is the gap (in source pixels) between adjacent cells. Kenney's
    // roguelike packs ship with a 1-pixel gutter between every 16×16 cell —
    // ignoring it makes deep-row sprites drift up by `row` pixels and render
    // halves of two cells stacked together (the "character bottom half on top"
    // bug). Set `padding: 1` on every roguelike sheet; leave 0 for packed
    // sheets (e.g. roguelikeCity_packed.png is gutter-free).
    constructor(src, frameW, frameH, padding = 0) {
        this.img     = new Image();
        this.frameW  = frameW;
        this.frameH  = frameH;
        this.padding = padding;
        this.loaded  = false;
        this.failed  = false;

        this._promise = new Promise((resolve) => {
            this.img.onload = () => {
                this.loaded = true;
                // Adding `padding` to the numerator handles Kenney's "missing
                // trailing gutter" — the last column/row doesn't have its
                // own trailing 1px, so the naive (W / (frameW+padding)) math
                // undercounts by one. With padding=1, the formula accounts for
                // the gutter between all cells and the implicit gutter after
                // the last column/row.
                const stride = this.frameW + this.padding;
                this.cols = Math.floor((this.img.width  + this.padding) / stride);
                this.rows = Math.floor((this.img.height + this.padding) / stride);
                resolve(true);
            };
            this.img.onerror = () => {
                this.failed = true;
                resolve(false);
            };
            this.img.src = src;
        });
    }

    get ready() { return this._promise; }

    // Draw by grid (col, row). Source coords account for any inter-cell
    // padding declared on the sheet — see constructor for context.
    drawFrame(ctx, col, row, x, y, destW, destH) {
        if (!this.loaded) return false;
        ctx.drawImage(
            this.img,
            col * (this.frameW + this.padding),
            row * (this.frameH + this.padding),
            this.frameW, this.frameH,
            x, y, destW ?? this.frameW, destH ?? this.frameH
        );
        return true;
    }

    // Draw by pixel region (for variable-sized sprites or precise extraction)
    drawRegion(ctx, sx, sy, sw, sh, dx, dy, dw, dh) {
        if (!this.loaded) return false;
        ctx.drawImage(this.img, sx, sy, sw, sh, dx, dy, dw ?? sw, dh ?? sh);
        return true;
    }
}

// ── Kenney sheets ────────────────────────────────────────────────────────────
//
// As of the Tiny overhaul, Violencetown's world/character art comes from two
// Kenney CC0 packs: **Tiny Dungeon** (dungeon tiles, heroes, monsters, items)
// and **Tiny Town** (town terrain, buildings, props, tools). Both are 12×11
// grids of 16×16 cells in a *packed* (gutter-free) atlas, so padding is 0 and
// the renderer's TILE_PX=32 destW/destH upscale gives a crisp 2× pixel look.
//
// Coordinates below were picked against labeled contact sheets generated by
// tools/gen_contact_sheet.py (tools/contact_tinyDungeon.png / _tinyTown.png).
// The legacy roguelike sheets remain bundled but are no longer referenced.

const K    = './assets-placeholder/kenney';
const TINY = `${K}/tiny`;

const TINY_DUNGEON = `${TINY}/dungeon/tinyDungeon_packed.png`;  // dungeon tiles, heroes, monsters, items
const TINY_TOWN    = `${TINY}/town/tinyTown_packed.png`;        // town terrain, buildings, props, tools

export const SHEETS = {
    // Tiny packs — the two atlases every coord map below references by key.
    // Packed (no inter-cell gutter), so padding stays 0.
    tinyDungeon:  { src: TINY_DUNGEON, frameW: 16, frameH: 16 },
    tinyTown:     { src: TINY_TOWN,    frameW: 16, frameH: 16 },

    // World-dressing (Kenney CC0): the packed roguelikeCity atlas — cars,
    // building facades, lampposts, storefronts. Gutter-free → padding 0; tiles
    // reference it via pixel-region refs (drawRegion).
    roguelikeCity: { src: `${K}/roguelikeCity_packed.png`, frameW: 16, frameH: 16 },
    // The town car: the full-resolution side-view beater lifted straight from
    // roguelikeCity (orange left-facing car, src px 503–539 × 392–415) onto a
    // 48×48 transparent canvas, wheels resting low. The renderer stretches this
    // one frame over the 2×2-tile (64×64) footprint, so the bigger native art
    // reads crisp instead of pixel-doubling a tiny 32px cell. Drawn at
    // TOWN_TILE_SPRITE_MAP[19] (replaces the wooden-bucket placeholder).
    car:           { src: './assets/car.png', frameW: 48, frameH: 48 },

    // Kenney Emote Pack (Pixel, Style 1) — 16x16 down-tail speech balloons for
    // Town Clock ambient reactions + disposition faces. Horizontal strip packed
    // by tools/gen_emote_sheet.py; column order = EMOTE_SPRITES below. Packed
    // (no gutter), padding 0.
    emotes:       { src: `${K}/emotes_style1.png`, frameW: 16, frameH: 16 },

    // Alias for the hardcoded renderer reference:
    //   • renderer._drawPlayer reads `sprites.player` directly.
    player:       { src: TINY_DUNGEON, frameW: 16, frameH: 16 },

    // Procedural 9-slice UI panel — 48×144 atlas with three 48×48 variants
    // stacked vertically (base / dark / glow). Generated by tools/gen_ui_panel.py;
    // see ui-sprites.js drawPanelBig() for how the 16×16 cells get sampled.
    // Panels are drawn via drawRegion with explicit pixel rects, so the nominal
    // frameW/frameH below aren't used for panel sampling.
    uiPanel:      { src: './assets/ui_panel.png', frameW: 32, frameH: 32 },
};

// ── Sewer/dungeon tile coords (Tiny Dungeon pack) ───────────────────────────
// Tiny Dungeon: tan dungeon floors, gray stone-brick, iron grates, doors,
// banner/torch accents. All entries name `tinyDungeon` explicitly.

export const TILE_SPRITE_MAP = {
    0: null,                                      // wall  — dark fallback (intentional, frames the room)
    1: { sheet: 'tinyDungeon', col: 0, row: 4 },  // floor — clean tan dungeon stone
    2: { sheet: 'tinyDungeon', col: 8, row: 2 },  // sludge — stone hatch leaking green ooze
    3: { sheet: 'tinyDungeon', col: 4, row: 4 },  // gap — speckled tan floor variant
    4: { sheet: 'tinyDungeon', col: 0, row: 3 },  // grate — horizontal iron bars
    5: { sheet: 'tinyDungeon', col: 6, row: 3 },  // drain — floor with 4-square stone inset
    6: { sheet: 'tinyDungeon', col: 9, row: 4 },  // boss floor — clean gray stone-brick slab
    7: { sheet: 'tinyDungeon', col: 5, row: 2 },  // boss trigger — red banner on stone (accent)
    22: { sheet: 'tinyDungeon', col: 5, row: 3 }, // PORTCULLIS — spiked vertical gate
    23: { sheet: 'tinyDungeon', col: 3, row: 5 }, // BARRICADE — wooden crate front (destructible)
};

// ── Town tile coords (Tiny Town pack) ───────────────────────────────────────
// Tiny Town has rich terrain/buildings/fences but ships no urban props (cars,
// streetlights, manholes, trashcans). The packed roguelikeCity atlas has all
// of them — already registered in SHEETS and fetched on every boot, and
// already the source of the building-wall pick at 14 below. Ids 16, 18, 20
// and 21 draw from it too.
export const TOWN_TILE_SPRITE_MAP = {
    10: null,                                        // town wall edge — dark fallback (frames the map)
    11: { sheet: 'tinyTown', col: 1, row: 9 },       // sidewalk — light gray stone slab
    12: { sheet: 'tinyTown', col: 1, row: 2 },       // road — borderless dirt-field center (edge cells carry grass borders)
    13: { sheet: 'tinyTown', col: 0, row: 0 },       // grass — plain green
    14: { sheet: 'roguelikeCity', col: 1, row: 6 },  // building wall — red-brick city facade (world-dressing; was tinyTown tan brick)
    15: { sheet: 'tinyTown', col: 1, row: 7 },       // door — brown door in wood facade
    16: { sheet: 'roguelikeCity', col: 9, row: 24 }, // sewer entry — round manhole cover set in the pavement
    17: { sheet: 'tinyTown', col: 9, row: 3 },       // fence — vertical wood plank
    18: { sheet: 'roguelikeCity', col: 19, row: 13 }, // streetlight — lamp post, lit head viewed from above
    19: { sheet: 'car', col: 0, row: 0 },            // car — Kenney roguelikeCity beater (world-dressing; was the wooden-bucket placeholder)
    20: { sheet: 'roguelikeCity', col: 15, row: 15 }, // bench — wooden park bench, slatted seat on two legs
    21: { sheet: 'roguelikeCity', col: 0, row: 17 }, // trash can — green wheeled bin
};

// ── Item sprites (Tiny packs) ───────────────────────────────────────────────
// Pixel-region references; the renderer extracts these via drawRegion().
// 16-pixel grid: x = col*16, y = row*16 (cells are gutter-free in packed atlas).

export const ITEM_SPRITES = {
    // Equipment / junk — Tiny Dungeon (visual rhymes at the 24×24 inventory size):
    rock:    { sheet: 'tinyDungeon', x: 0 * 16,  y: 1 * 16,  w: 16, h: 16 },  // brown boulder/rubble
    pipe:    { sheet: 'tinyDungeon', x: 10 * 16, y: 8 * 16,  w: 16, h: 16 },  // plain sword = elongated pipe/club
    soap:    { sheet: 'tinyDungeon', x: 5 * 16,  y: 9 * 16,  w: 16, h: 16 },  // white potion = pale bar proxy
    bandage: { sheet: 'tinyDungeon', x: 7 * 16,  y: 9 * 16,  w: 16, h: 16 },  // red potion = healing-red proxy

    // Ambro (food) items — Tiny packs:
    boardwalk_burger: { sheet: 'tinyDungeon', x: 10 * 16, y: 6 * 16, w: 16, h: 16 },  // burger/bun stack (exact)
    hot_dog:          { sheet: 'tinyTown',    x: 9 * 16,  y: 7 * 16, w: 16, h: 16 },  // round bread loaf
    mystery_meat:     { sheet: 'tinyTown',    x: 10 * 16, y: 7 * 16, w: 16, h: 16 },  // ambiguous bun/meat lump
    tunnel_mushroom:  { sheet: 'tinyTown',    x: 5 * 16,  y: 2 * 16, w: 16, h: 16 },  // red-cap toadstools (exact)

    // Quest item — wall-mounted machine/meter box reads "mechanical".
    catalytic_converter: { sheet: 'tinyTown', x: 9 * 16, y: 4 * 16, w: 16, h: 16 },

    // ── Poitions (visual-pass, 2026-09-06) ──────────────────────────────────
    // All six rendered as the generic grey '?' glyph — the v0.20.0 headline
    // category, unreadable in the bag. The four skinny vials on row 10 carry
    // the four most-used; the two free fat bottles on row 9 take the rest.
    health_poition:   { sheet: 'tinyDungeon', x: 7 * 16, y: 10 * 16, w: 16, h: 16 },  // red vial
    mana_poition:     { sheet: 'tinyDungeon', x: 8 * 16, y: 10 * 16, w: 16, h: 16 },  // blue vial
    strength_poition: { sheet: 'tinyDungeon', x: 6 * 16, y: 10 * 16, w: 16, h: 16 },  // green vial
    speed_poition:    { sheet: 'tinyDungeon', x: 5 * 16, y: 10 * 16, w: 16, h: 16 },  // plain vial
    gold_poition:     { sheet: 'tinyDungeon', x: 6 * 16, y: 9  * 16, w: 16, h: 16 },  // green bottle — money green
    defence_poition:  { sheet: 'tinyDungeon', x: 8 * 16, y: 9  * 16, w: 16, h: 16 },  // blue bottle

    // ── Item icons, second pass (visual-pass, 2026-09-06) ───────────────────
    // Shortlist picks verified against the labeled contact sheets (tools/contact_*.png).
    tome_ray_blast: { sheet: 'tinyDungeon', x: 6 * 16,  y: 5 * 16, w: 16, h: 16 },  // closed brown book, front cover
    fire_bottle:    { sheet: 'tinyDungeon', x: 5 * 16,  y: 2 * 16, w: 16, h: 16 },  // red-orange flame emblem (boss-trigger banner art) — took this over tinyTown (11,7)'s red/white canister, which has no actual flame shape
    chain:          { sheet: 'tinyDungeon', x: 0 * 16,  y: 3 * 16, w: 16, h: 16 },  // horizontal iron bars — reads as links at icon size
    burger_fries:   { sheet: 'tinyDungeon', x: 5 * 16,  y: 8 * 16, w: 16, h: 16 },  // nested-square box icon — passable fries carton
    wererat_fur:    { sheet: 'tinyTown',    x: 10 * 16, y: 8 * 16, w: 16, h: 16 },  // brown satchel/pouch
};

// NOT a source for these: `roguelikeChar_transparent.png` is bundled and looks
// like a character pack, but it is a PAPER-DOLL kit — bare bodies in column one,
// then separate torso, helmet, hair and weapon layers meant to be composited.
// There are no finished characters in it. Using it means building a layer
// compositor, not picking a cell. Checked 2026-09-06; don't re-open it lightly.
//
// ── Enemy/character sprites (Tiny Dungeon pack) ─────────────────────────────
// Tiny sprites are single-cell (no facing/animation frames), so every entry
// is `static: true`. See _drawEnemies in renderer.js for the static draw.
//
// The sewer's creature set is five types, not six — Violet/Red/Ghost Fungus
// and the Fungus King, placed by sewer-map.json, plus Rat, which
// sewer-setpiece.js spawns in the other three's place once the "escape the
// sewer" gauntlet starts (only the King survives that conversion). An earlier
// version of this note also counted a "Sewer Monster"; nothing in the
// codebase spawns one any more. All five are mapped to distinct creature
// cells so they never look alike. Zone-exclusive enemies (Greedy Green /
// Clown / Skeleton, in Factory / Circus / Graveyard) may reuse a creature
// read since they can't co-occur with the sewer set. Tiny Dungeon ships no
// literal mushroom / clown / skeleton sprite —
// those are flagged compromises (see the overhaul notes / verify in-browser).

export const ENEMY_SPRITES = {
    // Sewer set — six distinct creatures:
    'Violet Fungus': { sheet: 'tinyDungeon', col: 0, row: 10, static: true }, // orange spider — creepy crawler
    'Red Fungus':    { sheet: 'tinyDungeon', col: 2, row: 9,  static: true }, // red crab — reddish creature
    'Fungus King':   { sheet: 'tinyDungeon', col: 1, row: 9,  static: true }, // orange ogre — biggest/boss read
    'Ghost Fungus':  { sheet: 'tinyDungeon', col: 0, row: 9,  static: true }, // green ghost — most fungal/spectral
    // Rat: (3,9) is a HOODED FIGURE, not a rat — the old comment called the
    // robe front a "bib". The pack's actual rats are on the bottom row, beside
    // the vials. Canyon rats have been rendering as robed people all along.
    'Rat': { sheet: 'tinyDungeon', col: 3, row: 10, static: true }, // brown rat, curved body and tail

    // Merchant / bosses — humanoid cells:
    // Carrion: was (2,7), shared with Pike. (3,9) is freed by the Rat move and
    // is a better read for a carrion-merchant anyway — gaunt and hooded.
    // Pike keeps (2,7) to itself.
    'Carrion': { sheet: 'tinyDungeon', col: 3, row: 9, static: true }, // hooded, gaunt — the freed cell
    'Boss':    { sheet: 'tinyDungeon', col: 0, row: 8, static: true }, // knight helmet — Borgir employer
    'Wererat': { sheet: 'tinyDungeon', col: 3, row: 7, static: true }, // horned viking — hulking were-rat brute

    // Town — ambient Violencians. A POOL, not one cell: every citizen used to be
    // tinyDungeon (4,7), a plain brown-haired figure whose palette and silhouette
    // read as the player at (1,7) — so the whole town looked like eight copies of
    // you. (4,7) is retired for exactly that reason.
    //
    // Each cell here belongs to a type that never shares town or downtown with a
    // Violencian, so the reuse is free (verified by script; tests/sprite-coverage
    // enforces it). `col`/`row` mirror variants[0] so every consumer that reads
    // the flat shape — content-validate, the coverage test — keeps working.
    'Violencian': {
        sheet: 'tinyDungeon', col: 0, row: 7, static: true,
        variants: [
            { col: 0, row: 7 },  // purple-robed figure with a staff
            { col: 1, row: 8 },  // visored plate
            { col: 2, row: 8 },  // brown hair, work smock
            { col: 4, row: 8 },  // white-haired elder in a cloak
            { col: 3, row: 9 },  // hooded and gaunt
        ],
    },

    // Canyon — Pike the ageless prospector (reuses the gaunt robed-monk cell; a
    // proper grizzled-prospector read is a later sprite-picker pass).
    'Pike': { sheet: 'tinyDungeon', col: 2, row: 7, static: true }, // bald robed monk — gaunt, weathered

    // Zone-exclusive enemies (compromise picks — no clown/skeleton art exists):
    'Greedy Green':     { sheet: 'tinyDungeon', col: 4, row: 9,  static: true }, // green-bandana goblin
    'Carnival Clown':   { sheet: 'tinyDungeon', col: 0, row: 7,  static: true }, // purple mage — most colorful humanoid
    'Rattling Skeleton':{ sheet: 'tinyDungeon', col: 1, row: 10, static: true }, // white ghost — pale/bony proxy

    // ── Interior counter-NPCs and one-offs (visual-pass, 2026-09-06) ─────────
    // These types had NO entry, so each rendered as the flat #cc4433 fallback
    // box in _drawEnemySprite on every normal run. Five take the last unused
    // Tiny Dungeon humanoid cells; the rest reuse a cell from a zone they can
    // never share (tests/sprite-coverage.test.js will enforce that).
    'Banker':   { sheet: 'tinyDungeon', col: 4, row: 8, static: true }, // white-haired elder in a cloak — old money
    'Operator': { sheet: 'tinyDungeon', col: 1, row: 8, static: true }, // visored full plate — casino pit boss as bouncer
    'Cook':     { sheet: 'tinyDungeon', col: 2, row: 8, static: true }, // young figure in an apron-ish smock
    'Vendor':   { sheet: 'tinyDungeon', col: 3, row: 8, static: true }, // long hair, purple dress

    // Reuses, each from a zone the holder cannot co-occur with:
    'Stranger':   { sheet: 'tinyDungeon', col: 2, row: 7, static: true }, // Pike's gaunt skull-faced figure; Pike is canyon, this is downtown
    'Bootlegger': { sheet: 'tinyDungeon', col: 3, row: 7, static: true }, // Wererat's horned brute; Wererat is sewer-only, this is town
    'Puck':       { sheet: 'tinyDungeon', col: 0, row: 8, static: true }, // Boss's knight helm; Boss is Borgir, this is the factory

    // Not a person: a puzzleWall growth blocking a sewer pipe.
    'Sludge Bloom': { sheet: 'tinyDungeon', col: 8, row: 2, static: true }, // stone hatch leaking green ooze
};

// Which variant a given entity shows. Deterministic on the entity's identity,
// so a citizen looks the same every time you see them and across save/reload —
// a crowd that reshuffles on every frame is worse than a uniform one.
//
// Falls back to position when an entity has no id: still stable, still varied.
// Entries with no `variants` are returned untouched, so this is safe to call on
// every sprite lookup.
export function spriteVariant(info, entity) {
    if (!info?.variants?.length) return info;
    const key = String(entity?.id ?? `${entity?.x},${entity?.y}`);
    let h = 2166136261;                       // FNV-1a
    for (let i = 0; i < key.length; i++) {
        h ^= key.charCodeAt(i);
        h = Math.imul(h, 16777619);
    }
    const v = info.variants[(h >>> 0) % info.variants.length];
    return { ...info, col: v.col, row: v.row };
}

// Containers — replaces the procedural brown box in _drawContainers, which
// renderer.js flagged as a polish-pass placeholder.
export const CONTAINER_SPRITES = {
    closed: { sheet: 'tinyDungeon', col: 5, row: 7, static: true },
    open:   { sheet: 'tinyDungeon', col: 6, row: 7, static: true },
    full:   { sheet: 'tinyDungeon', col: 7, row: 7, static: true },
};

// Player sprite — Tiny Dungeon (1,7) = brown adventurer with cap + satchel,
// the natural read for a burger-delivery courier. Drawn via `sprites.player`.
export const PLAYER_SPRITE = { sheet: 'player', col: 1, row: 7, static: true };

// ── Props (tall, ground-anchored overlay objects — depth/verticality) ───────
// Unlike tiles (always one cell, drawn flat), props render TALLER than a single
// tile, anchored at their base tile, and depth-sort with the cast so the player
// can walk in front of and behind them. Source is a pixel region (drawRegion) so
// a multi-cell sprite scales uniformly at the game's 2x — no pixel-ratio break.
//   sx/sy/sw/sh — source rect in the sheet (16px grid; packed = gutter-free).
//   wTiles/hTiles — tiles the drawn sprite spans; the base (collision) tile is
//   the bottom-center one. So a 2x2 sprite overhangs its base by one tile up and
//   half a tile to each side, and the player walks behind that overhang.
export const PROP_SPRITES = {
    // Tiny Town tall conifer — 1x2 cells (col 4, rows 0-1) → 32x64 at 2x. One
    // tile wide, two tall: a clean, narrow trunk-and-canopy that reads as a real
    // tree. The player is occluded only when directly behind it (same column),
    // never when merely passing alongside. shadowRx/Ry size the trunk's pool.
    tree: { sheet: 'tinyTown', sx: 4 * 16, sy: 0, sw: 16, sh: 32, wTiles: 1, hTiles: 2, shadowRx: 12, shadowRy: 4.5 },
};

// ── Emote balloons (Kenney Emote Pack, Pixel Style 1) ───────────────────────
// Column index into the `emotes` strip (game/assets-placeholder/kenney/
// emotes_style1.png, packed by tools/gen_emote_sheet.py). Drawn above an NPC's
// head as a transient speech balloon when an ambient reaction fires — the
// placeholder grunt text ([Hrm.]/[Tch.]) made visual. KEEP IN SYNC with that
// script's ORDER list.
export const EMOTE_SPRITES = {
    dots1: 0, dots2: 1, dots3: 2, question: 3, exclamation: 4, sleep: 5,
    music: 6, anger: 7, heart: 8, idea: 9, laugh: 10, star: 11,
    drop: 12, faceHappy: 13, faceAngry: 14, faceSad: 15, alert: 16, swirl: 17,
};

// ── Zone tile coords (Circus / Factory / Graveyard) ─────────────────────────
// These three zones previously rendered as flat fallbackColor rectangles
// (no sprite refs anywhere). First-pass picks below render real art for the
// 12 tile ids defined in data.js. Pick verification was done via the
// sprite-picker tool (game/sprite-picker.html) at the correct stride.
//
// `sheet:` names the SpriteSheet key; renderer._drawTiles resolves it
// against `game.renderer.sprites[sheet]`. Every entry must name a sheet explicitly.

export const ZONE_TILE_SPRITE_MAP = {
    // Circus — Tiny Town terrain. Striped awning art does exist — green/white
    // and orange/white awnings in roguelikeCity_packed.png — but swapping it
    // in is out of scope for this pass; red roof shingles still stand in for
    // TENT_STRIPE (flagged compromise).
    30: { sheet: 'tinyTown', col: 1, row: 2 },   // CIRCUS_GROUND — packed dirt/sand
    31: { sheet: 'tinyTown', col: 4, row: 4 },   // TENT_STRIPE   — red roof shingles (awning proxy)
    32: { sheet: 'tinyTown', col: 2, row: 0 },   // CONFETTI      — grass dotted with orange flowers
    33: { sheet: 'tinyTown', col: 4, row: 3 },   // SAWDUST       — packed tan dirt

    // Factory — Tiny Dungeon gray stone. No conveyor art; wood slats proxy it.
    40: { sheet: 'tinyDungeon', col: 9, row: 4 }, // FACTORY_FLOOR — clean gray stone slab
    41: { sheet: 'tinyDungeon', col: 4, row: 3 }, // FACTORY_WALL  — gray brick wall
    42: { sheet: 'tinyDungeon', col: 8, row: 2 }, // GOO_VISUAL    — green ooze hatch
    43: { sheet: 'tinyDungeon', col: 4, row: 6 }, // CONVEYOR_VIS  — wood slats (belt proxy)

    // Graveyard — Tiny Town dirt/foliage + Tiny Dungeon stone cross.
    50: { sheet: 'tinyTown',    col: 1, row: 1 }, // GRAVE_DIRT    — brown dirt patch
    51: { sheet: 'tinyDungeon', col: 4, row: 5 }, // GRAVESTONE    — gray stone cross
    52: { sheet: 'tinyTown',    col: 1, row: 0 }, // DEAD_GRASS    — tufted grass (ground fill; toadstools tiled too busy)
    53: { sheet: 'tinyTown',    col: 9, row: 3 }, // IRON_FENCE    — wood fence (no iron railing in pack)
};

// ── Phase B TODO ────────────────────────────────────────────────────────────
// All coordinates above are first-pass picks from visual inspection of the
// Kenney sheets. Expect to revisit them as the game's visual identity firms
// up. Particularly worth investing in:
//   • A consistent "Violencetown" character palette across the 5 zone enemies
//   • Better tile-to-zone matching (sewer vs cave should look distinct)
//   • Item icons that read clearly at TILE_PX-8 hotbar size
// Iteration loop: edit coords here → reload page → screenshot → adjust.

// ── Loader ───────────────────────────────────────────────────────────────────

export async function loadAllSprites() {
    const loaded = {};
    const promises = [];

    for (const [key, def] of Object.entries(SHEETS)) {
        const sheet = new SpriteSheet(def.src, def.frameW, def.frameH, def.padding ?? 0);
        loaded[key] = sheet;
        promises.push(sheet.ready);
    }

    await Promise.all(promises);

    let ok = 0, fail = 0;
    for (const [, sheet] of Object.entries(loaded)) {
        if (sheet.loaded) ok++; else fail++;
    }

    return { sheets: loaded, ok, fail };
}
